const SET_ADDRESS = "SET_ADDRESS";
const SET_COORDINATE = "SET_COORDINATE";
const SET_MARKER_OPEN = "SET_MARKER_OPEN";
const SET_FULL_ADDRESS = "SET_FULL_ADDRESS";

export {
    SET_ADDRESS,
    SET_COORDINATE,
    SET_MARKER_OPEN,
    SET_FULL_ADDRESS,
}